image:
  tag: 'latest-arm-8200306c9cd6cf3efa9225b81bf98c546073f4a4'

appUrl: 'https://theses.stg.df-app.ch'

azureAd:
  clientId: ''
  clientSecret: ''
  tenantId: ''

secretName: stg-thesisplatform-secrets

ingress:
  hosts:
    - host: theses.stg.df-app.ch
      paths:
        - /
  tls:
    - secretName: thesis-platform-stage-tls
      hosts:
        - theses.stg.df-app.ch
