image:
  tag: 'latest-arm-a4362b18c8e593a96faf3572db51c44979d3340c'

env: stg
appUrl: 'https://theses.stg.df-app.ch'

stagingSafety:
  grantAllAdmins: 'true'

azureAd:
  clientId: ''
  clientSecret: ''
  tenantId: ''

secretName: stg-thesisplatform-secrets

ingress:
  hosts:
    - host: theses.stg.df-app.ch
      paths:
        - /
  tls:
    - secretName: thesis-platform-stage-tls
      hosts:
        - theses.stg.df-app.ch
