image:
  tag: 'latest-arm-763157d0a3b4d0996b8829f45a0e5009a8476ff1'

ingress:
  hosts:
    - host: theses.stg.df-app.ch
      paths:
        - /
  tls:
    - secretName: thesis-platform-stage-tls
      hosts:
        - theses.stg.df-app.ch
