export enum ProposalStatus {
  OPEN = 'OPEN',
  WAITING_FOR_STUDENT = 'WAITING_FOR_STUDENT',
  WAITING_FOR_SUPERVISOR = 'WAITING_FOR_SUPERVISOR',
  MATCHED_TENTATIVE = 'MATCHED_TENTATIVE',
  MATCHED = 'MATCHED',
  SUBMITTED = 'SUBMITTED',
  REVIEWED = 'REVIEWED',
  CLOSED = 'CLOSED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum ApplicationStatus {
  OPEN = 'OPEN',
  DECLINED = 'DECLINED',
  ACCEPTED = 'ACCEPTED',
  ACCEPTED_TENTATIVE = 'ACCEPTED_TENTATIVE',
  WITHDRAWN = 'WITHDRAWN',
}

export enum ProposalType {
  STUDENT = 'STUDENT',
  SUPERVISOR = 'SUPERVISOR',
}

export enum ProposalFeedbackType {
  ACCEPTED = 'ACCEPTED',
  ACCEPTED_TENTATIVE = 'ACCEPTED_TENTATIVE',
  DECLINED_LACKING_INTEREST = 'DECLINED_LACKING_INTEREST',
  DECLINED_LANGUAGE = 'DECLINED_LANGUAGE',
  DECLINED_PERSONAL_WORKLOAD = 'DECLINED_PERSONAL_WORKLOAD',
  DECLINED_WORKLOAD = 'DECLINED_WORKLOAD',
  REJECTED_CONTENT = 'REJECTED_CONTENT',
  REJECTED_FORMAT_UNSUITABLE = 'REJECTED_FORMAT_UNSUITABLE',
  REJECTED_NOT_CLEAR = 'REJECTED_NOT_CLEAR',
  REJECTED_NOT_SCIENTIFIC = 'REJECTED_NOT_SCIENTIFIC',
  REJECTED_TOO_BROAD = 'REJECTED_TOO_BROAD',
  REJECTED_TOPIC_AREA_INVALID = 'REJECTED_TOPIC_AREA_INVALID',
}

export enum UserRole {
  STUDENT = 'STUDENT',
  SUPERVISOR = 'SUPERVISOR',
  DEVELOPER = 'DEVELOPER',
}

export enum TopicAreas {
  banking_and_insurance = 'Banking and Insurance',
  corporate_finance = 'Corporate Finance',
  financial_economics = 'Financial Economics',
  quantitative_finance = 'Quantitative Finance',
  sustainable_finance = 'Sustainable Finance',
}

export enum Department {
  DF = 'DF',
  IBW = 'IBW',
}