export enum ProposalStatus {
  OPEN = 'OPEN',
  WAITING_FOR_STUDENT = 'WAITING_FOR_STUDENT',
  WAITING_FOR_SUPERVISOR = 'WAITING_FOR_SUPERVISOR',
  MATCHED = 'MATCHED',
  SUBMITTED = 'SUBMITTED',
  REVIEWED = 'REVIEWED',
  CLOSED = 'CLOSED',
}

export enum ProposalType {
  STUDENT = 'STUDENT',
  SUPERVISOR = 'SUPERVISOR',
}

export enum ProposalFeedbackType {
  ACCEPTED = 'ACCEPTED',
  REJECTED_CONTENT = 'REJECTED_CONTENT',
  REJECTED_FORMAT = 'REJECTED_FORMAT',
  DECLINED_INTEREST = 'DECLINED_INTEREST',
  DECLINED_WORKLOAD = 'DECLINED_WORKLOAD',
}
