appSecret: '$NEXTAUTH_SECRET'
appUrl: '$APP_URL'
env: stg

stagingSafety:
  enableExternalFlows: '$STAGING_ENABLE_EXTERNAL_FLOWS'
  emailRedirectTo: '$STAGING_EMAIL_REDIRECT_TO'
  grantAllAdmins: 'true'

image:
  tag: '$APP_VERSION'

flows:
  secret: '$FLOW_SECRET'
  application: '$APPLICATION_URL'
  proposalFeedback: '$PROPOSAL_FEEDBACK_URL'
  proposalPublish: '$PROPOSAL_PUBLISH_URL'
  applicationAcceptance: '$APPLICATION_ACCEPTANCE_URL'
  emailNotification: '$EMAIL_NOTIFICATION_URL'
  faqUrlStudent: '$FAQ_URL_STUDENT'
  faqUrlSupervisor: '$FAQ_URL_SUPERVISOR'

cleverreach:
  clientId: '$CLEVERREACH_CLIENT_ID'
  clientSecret: '$CLEVERREACH_CLIENT_SECRET'
  senderName: '$CLEVERREACH_SENDER_NAME'
  senderEmail: '$CLEVERREACH_SENDER_EMAIL'
  mailingNamePrefix: '$CLEVERREACH_MAILING_NAME_PREFIX'
  templateThesisProposal: '$CLEVERREACH_TEMPLATE_THESIS_PROPOSAL'
  subjectThesisProposal: '$CLEVERREACH_SUBJECT_THESIS_PROPOSAL'
  filterTheses: '$CLEVERREACH_FILTER_THESES'
  adminUrl: '$CLEVERREACH_ADMIN_URL'

azureAd:
  clientId: '$AZURE_AD_CLIENT_ID'
  clientSecret: '$AZURE_AD_CLIENT_SECRET'
  tenantId: '$AZURE_AD_TENANT_ID'

auth0:
  issuer: '$AUTH0_ISSUER'
  clientId: '$AUTH0_CLIENT_ID'
  clientSecret: '$AUTH0_CLIENT_SECRET'

azureBlob:
  accessKey: '$AZURE_STORAGE_ACCOUNT_ACCESS_KEY'

database:
  url: '$DATABASE_URL'

ingress:
  hosts:
    - host: theses.stage.env.bf-app.ch
      paths:
        - /
  tls:
    - secretName: thesis-platform-stage-tls
      hosts:
        - theses.stage.env.bf-app.ch
