env: ""

azureAd:
  clientId: ""
  clientSecret: ""
  tenantId: ""

auth0:
  clientId: ""
  clientSecret: ""
  issuer: ""

azureBlob:
  accessKey: ""

database:
  url: ""

appSecret: ""

replicaCount: 1

image:
  repository: ghcr.io/uzh-bf/thesis-platform
  tag: main
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 256m
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: theses.bf.uzh.ch
      paths:
        - /
  tls:
    - secretName: thesis-platform-tls
      hosts:
        - theses.bf.uzh.ch

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m

annotations: {}
podAnnotations: {}
