services:
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: thesis
      POSTGRES_PASSWORD: thesis
      POSTGRES_DB: main
    ports:
      - 5432:5432

  next:
    build: .
    environment:
      NEXTAUTH_SECRET: 'N/l1mmMLDNwKaTlID6v8UyOjqu9VdGRLGjkF3S7a6vo='
      AZURE_AD_CLIENT_ID: '366366bc-802b-4a5c-8f2c-89be11ba47c5'
      AZURE_AD_CLIENT_SECRET: 'zo_8Q~VeNfTo3ig-uFgZJ0IQ63etHguz9Nqbccc~'
      AZURE_AD_TENANT_ID: 'c7e438db-e462-4c22-a90a-c358b16980b3'
      EMAIL_SERVER_USER: 'AKIAYSOSGZVT2KT7MMTY'
      EMAIL_SERVER_PASSWORD: 'BA5Fwl/bOS4HHx8REbzMZO+s7umfE7D8eaGJNbnyPrDP'
      EMAIL_SERVER_HOST: email-smtp.eu-west-1.amazonaws.com
      EMAIL_SERVER_PORT: 587
      EMAIL_FROM: theses-signin@bf-app.ch
      DATABASE_URL: 'sqlserver://uzhbfthesisassignment.database.windows.net:1433;database=thesis-assignment-dev;user=superuser@uzhbfthesisassignment;password=XCH5bQZ7T5fucgmQCkMMhMU4r24dMY86e;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;'
    ports:
      - 3000:3000
