services:
  mysql:
    image: docker.io/library/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: thesis
      MYSQL_DATABASE: thesis
      MYSQL_USER: thesis
      MYSQL_PASSWORD: thesis
    ports:
      - 3306:3306
    networks:
      - thesis-platform
    volumes:
      - /var/lib/mysql

  next:
    profiles:
      - app
    build: .
    environment:
      NEXTAUTH_SECRET: 'abcdabcd'
      EMAIL_FROM: theses-signin@bf-app.ch
      EMAIL_SERVER_HOST: sendria
      EMAIL_SERVER_PORT: 1025
      EMAIL_SERVER_USER:
      EMAIL_SERVER_PASSWORD:
      DATABASE_URL: 'mysql://thesis:thesis@localhost:3306/thesis'
    ports:
      - 3000:3000
    networks:
      - thesis-platform

  mailhog:
    image: docker.io/mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - thesis-platform

networks:
  thesis-platform:
