services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: rtScuF7pnvCiG4gg5b3qgvkn
    ports:
      - 1433:1433
    networks:
      - thesis-platform

  next:
    profiles:
      - app
    build: .
    environment:
      NEXTAUTH_SECRET: 'abcdabcd'
      EMAIL_FROM: theses-signin@bf-app.ch
      EMAIL_SERVER_HOST: sendria
      EMAIL_SERVER_PORT: 1025
      EMAIL_SERVER_USER:
      EMAIL_SERVER_PASSWORD:
      DATABASE_URL: 'sqlserver://localhost:1433;database=main;user=sa;password=rtScuF7pnvCiG4gg5b3qgvkn;trustServerCertificate=true;'
    ports:
      - 3000:3000
    networks:
      - thesis-platform

  sendria:
    profiles:
      - app
    image: msztolcman/sendria:v2.2.2.0
    ports:
      - 1025:1025
      - 1080:1080
    networks:
      - thesis-platform

networks:
  thesis-platform:
