apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thesis-platform.fullname" . }}
  labels:
    {{- include "thesis-platform.labels" . | nindent 4 }}
data:
  AZURE_AD_CLIENT_ID: {{ .Values.azureAd.clientId | quote }}
  AZURE_AD_TENANT_ID: {{ .Values.azureAd.tenantId | quote }}
  EMAIL_SERVER_USER: {{ .Values.email.user | quote }}
  EMAIL_SERVER_HOST: {{ .Values.email.host | quote }}
  EMAIL_SERVER_PORT: {{ .Values.email.port | quote }}
  EMAIL_FROM: {{ .Values.email.from | quote }}
  NEXTAUTH_URL: {{ .Values.appUrl | quote }}
