apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thesis-platform.fullname" . }}
  labels:
    {{- include "thesis-platform.labels" . | nindent 4 }}
data:
  AUTH0_CLIENT_ID: {{ .Values.auth0.clientId | quote }}
  AUTH0_ISSUER: {{ .Values.auth0.issuer | quote }}
  AZURE_AD_CLIENT_ID: {{ .Values.azureAd.clientId | quote }}
  AZURE_AD_TENANT_ID: {{ .Values.azureAd.tenantId | quote }}
  NEXTAUTH_URL: {{ .Values.appUrl | quote }}
