apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thesis-platform.fullname" . }}
  labels:
    {{- include "thesis-platform.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "thesis-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with merge .Values.podAnnotations .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        timestamp: {{ now | quote }}
    {{- end }}
      labels:
        {{- include "thesis-platform.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "thesis-platform.fullname" . }}
            - secretRef:
                name: {{ include "thesis-platform.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
