apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thesis-platform.fullname" . }}
  labels:
    {{- include "thesis-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLOW_SECRET: {{ .Values.flows.secret | quote }}
  AUTH0_CLIENT_SECRET: {{ .Values.auth0.clientSecret | quote }}
  AZURE_AD_CLIENT_SECRET: {{ .Values.azureAd.clientSecret | quote }}
  AZURE_STORAGE_ACCOUNT_ACCESS_KEY: {{ .Values.azureBlob.accessKey | quote }}
  DATABASE_URL: {{ .Values.database.url | quote }}
  NEXTAUTH_SECRET: {{ .Values.appSecret | quote }}
  APPLICATION_URL: {{ .Values.flows.application | quote }}
  PROPOSAL_FEEDBACK_URL: {{ .Values.flows.proposalFeedback | quote }}
