apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thesis-platform.fullname" . }}
  labels:
    {{- include "thesis-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.appSecret | quote }}
  AZURE_AD_CLIENT_SECRET: {{ .Values.azureAd.clientSecret | quote }}
  EMAIL_SERVER_PASSWORD: {{ .Values.email.password | quote }}
  DATABASE_URL: {{ .Values.database.url | quote }}
