apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thesis-platform.fullname" . }}
  labels:
    {{- include "thesis-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLOW_SECRET: {{ .Values.flows.secret | quote }}
  AUTH0_CLIENT_SECRET: {{ .Values.auth0.clientSecret | quote }}
  AZURE_AD_CLIENT_SECRET: {{ .Values.azureAd.clientSecret | quote }}
  AZURE_STORAGE_ACCOUNT_ACCESS_KEY: {{ .Values.azureBlob.accessKey | quote }}
  DATABASE_URL: {{ .Values.database.url | quote }}
  NEXTAUTH_SECRET: {{ .Values.appSecret | quote }}
  APPLICATION_URL: {{ .Values.flows.application | quote }}
  PROPOSAL_FEEDBACK_URL: {{ .Values.flows.proposalFeedback | quote }}
  PROPOSAL_PUBLISH_URL: {{ .Values.flows.proposalPublish | quote }}
  APPLICATION_ACCEPTANCE_URL: {{ .Values.flows.applicationAcceptance | quote }}
  EMAIL_NOTIFICATION_URL: {{ .Values.flows.emailNotification | quote }}
  NEXT_PUBLIC_FAQ_URL_STUDENT: {{ .Values.flows.faqUrlStudent | quote }}
  NEXT_PUBLIC_FAQ_URL_SUPERVISOR: {{ .Values.flows.faqUrlSupervisor | quote }}
  CLEVERREACH_CLIENT_ID: {{ .Values.cleverreach.clientId | quote }}
  CLEVERREACH_CLIENT_SECRET: {{ .Values.cleverreach.clientSecret | quote }}
  CLEVERREACH_SENDER_NAME: {{ .Values.cleverreach.senderName | quote }}
  CLEVERREACH_SENDER_EMAIL: {{ .Values.cleverreach.senderEmail | quote }}
  CLEVERREACH_MAILING_NAME_PREFIX: {{ .Values.cleverreach.mailingNamePrefix | quote }}
  CLEVERREACH_TEMPLATE_THESIS_PROPOSAL: {{ .Values.cleverreach.templateThesisProposal | quote }}
  CLEVERREACH_SUBJECT_THESIS_PROPOSAL: {{ .Values.cleverreach.subjectThesisProposal | quote }}
  CLEVERREACH_FILTER_THESES: {{ .Values.cleverreach.filterTheses | quote }}
  CLEVERREACH_ADMIN_URL: {{ .Values.cleverreach.adminUrl | quote }}
