apiVersion: v1
kind: Service
metadata:
  name: {{ include "thesis-platform.fullname" . }}
  labels:
    {{- include "thesis-platform.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "thesis-platform.selectorLabels" . | nindent 4 }}
