appSecret: '$NEXTAUTH_SECRET'
appUrl: '$APP_URL'
env: prd

stagingSafety:
  grantAllAdmins: ''

image:
  tag: '$APP_VERSION'

flows:
  secret: '$FLOW_SECRET'
  application: '$APPLICATION_URL'
  proposalFeedback: '$PROPOSAL_FEEDBACK_URL'
  proposalPublish: '$PROPOSAL_PUBLISH_URL'
  applicationAcceptance: '$APPLICATION_ACCEPTANCE_URL'
  emailNotification: '$EMAIL_NOTIFICATION_URL'
  faqUrlStudent: '$FAQ_URL_STUDENT'
  faqUrlSupervisor: '$FAQ_URL_SUPERVISOR'

cleverreach:
  clientId: '$CLEVERREACH_CLIENT_ID'
  clientSecret: '$CLEVERREACH_CLIENT_SECRET'
  senderName: '$CLEVERREACH_SENDER_NAME'
  senderEmail: '$CLEVERREACH_SENDER_EMAIL'
  mailingNamePrefix: '$CLEVERREACH_MAILING_NAME_PREFIX'
  templateThesisProposal: '$CLEVERREACH_TEMPLATE_THESIS_PROPOSAL'
  subjectThesisProposal: '$CLEVERREACH_SUBJECT_THESIS_PROPOSAL'
  filterTheses: '$CLEVERREACH_FILTER_THESES'
  adminUrl: '$CLEVERREACH_ADMIN_URL'

azureAd:
  clientId: '$AZURE_AD_CLIENT_ID'
  clientSecret: '$AZURE_AD_CLIENT_SECRET'
  tenantId: '$AZURE_AD_TENANT_ID'

azureBlob:
  accessKey: '$AZURE_STORAGE_ACCOUNT_ACCESS_KEY'

database:
  url: '$DATABASE_URL'
