releases:
  - name: thesis-platform
    namespace: '{{ env "NAMESPACE" | default "thesis-platform-stage" }}'
    createNamespace: true
    chart: ./chart
    version: '{{ env "CHART_VERSION" | default "0.1.0" }}'
    installed: true
    kubeContext: bf-k8s463ba113
    values:
      - appSecret: '{{ requiredEnv "NEXTAUTH_SECRET" }}'
        appUrl: '{{ requiredEnv "APP_URL" }}'

        image:
          tag: '{{ requiredEnv "APP_VERSION" }}'

        flows:
          secret: '{{ requiredEnv "FLOW_SECRET" }}'
          application: '{{ requiredEnv "APPLICATION_URL" }}'
          proposalFeedback: '{{ requiredEnv "PROPOSAL_FEEDBACK_URL" }}'
          applicationAcceptance: '{{ requiredEnv "APPLICATION_ACCEPTANCE_URL" }}'

        azureAd:
          clientId: '{{ env "AZURE_AD_CLIENT_ID" }}'
          clientSecret: '{{ env "AZURE_AD_CLIENT_SECRET" }}'
          tenantId: '{{ env "AZURE_AD_TENANT_ID" }}'

        auth0:
          clientId: '{{ env "AUTH0_CLIENT_ID" }}'
          clientSecret: '{{ env "AUTH0_CLIENT_SECRET" }}'
          issuer: '{{ env "AUTH0_ISSUER" }}'

        azureBlob:
          accessKey: '{{ requiredEnv "AZURE_STORAGE_ACCOUNT_ACCESS_KEY" }}'

        database:
          url: '{{ requiredEnv "DATABASE_URL" }}'

        ingress:
          hosts:
            - host: '{{ requiredEnv "APP_DOMAIN" }}'
              paths:
                - /
          tls:
            - secretName: thesis-platform-tls
              hosts:
                - '{{ requiredEnv "APP_DOMAIN" }}'
