appSecret: '$NEXTAUTH_SECRET'
appUrl: '$APP_URL'

flows:
  secret: '$FLOW_SECRET'
  application: '$APPLICATION_URL'
  proposalFeedback: '$PROPOSAL_FEEDBACK_URL'
  applicationAcceptance: '$APPLICATION_ACCEPTANCE_URL'

azureAd:
  clientId: '$AZURE_AD_CLIENT_ID'
  clientSecret: '$AZURE_AD_CLIENT_SECRET'
  tenantId: '$AZURE_AD_TENANT_ID'

azureBlob:
  accessKey: '$AZURE_STORAGE_ACCOUNT_ACCESS_KEY'

database:
  url: '$DATABASE_URL'
