image:
  repository: ghcr.io/uzh-bf/thesis-platform-ibw
  tag: 'stable-arm-872b43455ccfb5ff8e33dee0a9aca6667875ca77'

env: prd_ibw
appUrl: 'https://theses.business.uzh.ch'

# Admin area is only reachable from the UZH network / VPN:
# 130.60.0.0/16 = institute and server networks
# 89.206.64.0/18 = WLAN, VPN, public network workstations
adminAllowedIpRanges: '130.60.0.0/16,89.206.64.0/18'

azureAd:
  clientId: ''
  clientSecret: ''
  tenantId: ''

secretName: prd-thesisplatform-ibw-secrets

ingress:
  annotations:
    cert-manager.io/cluster-issuer: k8s-crt-mgr-iss-prd-apps-default
  hosts:
    - host: theses.business.prd.df-app.ch
      paths:
        - /
    - host: theses.business.uzh.ch
      paths:
        - /
  tls:
    - secretName: thesis-platform-ibw-prod-tls
      hosts:
        - theses.business.prd.df-app.ch
        - theses.business.uzh.ch
