image:
  repository: ghcr.io/uzh-bf/thesis-platform-ibw
  tag: 'stable-arm-fc8de3d0660093c37b658a2825c8dbb08bc225f1'

env: prd_ibw
appUrl: 'https://theses.business.uzh.ch'

stagingSafety:
  grantAllAdmins: 'true'

azureAd:
  clientId: ''
  clientSecret: ''
  tenantId: ''

secretName: prd-thesisplatform-ibw-secrets

ingress:
  annotations:
    cert-manager.io/cluster-issuer: k8s-crt-mgr-iss-prd-apps-default
  hosts:
    - host: theses.business.prd.df-app.ch
      paths:
        - /
    - host: theses.business.uzh.ch
      paths:
        - /
  tls:
    - secretName: thesis-platform-ibw-prod-tls
      hosts:
        - theses.business.prd.df-app.ch
        - theses.business.uzh.ch
