image:
  tag: 'stable-arm-fcbc08c5bb80d4e4eb8aebdfe9d4a30d40591d04'

env: prd
appUrl: 'https://theses.df.uzh.ch'

# Admin area is only reachable from the UZH network / VPN:
# 130.60.0.0/16 = institute and server networks
# 89.206.64.0/18 = WLAN, VPN, public network workstations
adminAllowedIpRanges: '130.60.0.0/16,89.206.64.0/18'

azureAd:
  clientId: ''
  clientSecret: ''
  tenantId: ''

secretName: prd-thesisplatform-secrets

ingress:
  annotations:
    cert-manager.io/cluster-issuer: k8s-crt-mgr-iss-prd-apps-default
  hosts:
    - host: theses.prd.df-app.ch
      paths:
        - /
    - host: theses.bf.uzh.ch
      paths:
        - /
    - host: theses.df.uzh.ch
      paths:
        - /
  tls:
    - secretName: thesis-platform-prod-tls
      hosts:
        - theses.prd.df-app.ch
        - theses.bf.uzh.ch
        - theses.df.uzh.ch
